### PR TITLE
Update to laravel 9

### PR DESCRIPTION
**Pull request by nikolaynizruhin**

### CODE REVIEW

**Comment by driesvints** [comment]
Heya, thanks for this! But I think there's still much missing in order to move to Laravel v9. Have a look at the Laravel Shift here which can maybe help out? https://github.com/fullstackbelgium/fullstackbelgium.be/pull/77

**Comment by nikolaynizruhin** [comment]
Updated. Should be better now :)

**Comment by driesvints** [comment]
Hey @nikolaynizruhin, nice. There do appear to be some conflicts. Can you resolve those first?

**Comment by nikolaynizruhin** [comment]
Yes, I resolved them before, it says `This branch has no conflicts with the base branch` for me. Or am I missing something?

**Comment by driesvints** [comment]
I'm seeing this:

Screenshot 2022-02-20 at 11 04 36

**Comment by driesvints** [comment]
I can use other ways to merge though. Don't worry about it. I'll have a look at this as soon as I can. Thanks!

**Comment by driesvints** [comment]
Heya, I had to merge this locally unfortunately because I couldn't push to your remote. Thanks for this! 👏

**Pull request closed without merging**
